# Generated by Django 3.0.7 on 2020-07-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('university_building', models.IntegerField()),
            ],
            options={
                'db_table': 'room',
                'ordering': ('university_building',),
            },
        ),
    ]
