# Generated by Django 3.0.7 on 2020-07-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('official_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'teacher',
                'ordering': ('name',),
            },
        ),
    ]
