# Generated by Django 3.0.7 on 2020-07-20 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('groups', '0001_initial'),
        ('teachers', '0001_initial'),
        ('timeslots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=10)),
                ('day_of_week', models.IntegerField()),
                ('week_number', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='groups.Group')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='rooms.Room')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='teachers.Teacher')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='timeslots.TimeSlot')),
            ],
            options={
                'db_table': 'class',
            },
        ),
    ]
