# Generated by Django 3.0.7 on 2020-07-20 11:57

from django.db import migrations, models
from djangoapps.classes.models import Class


def transfer_old_group_relation(apps, schema_editor):
    class_model: Class = apps.get_model('classes', 'Class')
    for university_class in class_model.objects.all():
        university_class.groups_new.add(university_class.group)
        university_class.save()


class Migration(migrations.Migration):
    """
        Change relation between class-group from many-to-one --> many-to-many
    """

    dependencies = [
        ('groups', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='groups_new',
            field=models.ManyToManyField(related_name='classes_new', to='groups.Group'),
        ),

        migrations.RunPython(transfer_old_group_relation),
    ]
