# Generated by Django 3.0.7 on 2020-07-22 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('classes', '0002_class_groups_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='group',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='groups_new',
            new_name='groups',
        ),
    ]
